# Generated by Django 5.1 on 2026-06-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoppingpurchase',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
