# Generated by Django 5.1 on 2026-06-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_shoppingitem_recommended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingpurchase',
            name='payment_method',
            field=models.CharField(default='credit', max_length=32),
        ),
    ]
